PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE USER (
LOGIN TEXT NOT NULL,
PASSWORD TEXT NOT NULL
);
INSERT INTO USER VALUES('ylafkih','pass');
INSERT INTO USER VALUES('ayidbelh','pass2');
COMMIT;
